### ISSUE TITLE
Error in running lammps with pair-nequip

### ISSUE THREAD

**Issue by HojeChun** [mir-group/pair_nequip#23]
Thank you for distributing such an exciting project to the society.

I have been trying using nequip and came up with the trained potentials.

Now I wanted to run the multi-scale simulation with pair_nequip potential in lammps.

I compiled according to the instruction, but keep getting an error like below:

```
Total # of neighbors = 27926
Ave neighs/atom = 57.108384
Neighbor list builds = 2
Dangerous builds = 0
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 76
  Time step     : 0.001
Per MPI rank memory allocation (min/avg/max) = 3.059 | 3.059 | 3.059 Mbytes
Step PotEng KinEng TotEng Temp Volume
      76     -2010460    48.760029   -2010411.2          773        42875
corrupted double-linked list
[1]    112200 abort (core dumped)  lmp_nequip -in system.in
```

Like shown above, the error is raised right after the minimization step. The full log and input LAMMPS script can be found [here](https://gist.github.com/HojeChun/a3c002125ef85190a0f2839bc6b5c36a).

Thank you for reading.

**Comment by anjohan** [comment]
Hi,

From your minimization output
```  
Force max component initial, final = 23.158852 44838200.0
```
it looks like the minimization fails badly. Try to look at the resulting structure, and maybe do a `dump` at every minimization step.
