### ISSUE TITLE
Build LAMMPS with some error

### ISSUE THREAD

**Issue by lzcun** [mir-group/pair_nequip#45]
hello, 
I created a new conda environment with cuda11.8, pytorch version is 1.10.1 with py3.7_cuda11.3_cudnn8.2.0_0.
But when I build lammps  "make -j12", I meet the error as below:
![image](https://github.com/mir-group/pair_nequip/assets/82214631/c0e40268-7a7f-45a4-aad2-e518d4949a6a)
 I found that the file "lammps/cmake/CMakeLists.txt" did not need to change.  I am unsure how to resolve this error. Could you please provide me with some guidance or suggestions?
 Thank you!

**Comment by Linux-cpp-lisp** [comment]
See https://github.com/mir-group/pair_nequip/issues/33

**Comment by lzcun** [comment]
Thank you so much! It solved!
