### ISSUE TITLE
Apply nequip potential to a subsystem

### ISSUE THREAD

**Issue by duneandre** [mir-group/pair_nequip#48]
Hi,

I developed a machine-learning potential with nequip for a system made of Zn, C, H and O atoms. 
I am now adding methane to the system and trying to run MD simulations with LAMMPS. I use the hybrid pair style in LAMMPS, using nequip potential for the sub-part of the system on which the MLP was trained and using Lennard-Jones potential for interactions involving methane. 

However, `pair_nequip` is written so that `pair_coeff` expects `* *` as argument (`src/pair_nequip.cpp:146`), thus preventing the selection of particular atomic types. 
How can we apply nequip potential only to a sub-part of a system and not on all atoms?

Thanks,

Dune

**Comment by Linux-cpp-lisp** [comment]
Hi @duneandre ,

Thanks for your interest in our code!

It does not seem like this would be a straightforward change, and it would also require giving careful thought to how you train the model.   It may be possible to adapt `pair_nequip` to this purpose by somehow filtering the neighborlist before it is passed to the model, but this is not a supported usecase at this time.
