### ISSUE TITLE
symbol lookup error: libtorch_cpu.so

### ISSUE THREAD

**Issue by phys-chem** [mir-group/pair_nequip#49]
When I run pair nequip with compiled LAMMPS, I have this error:
`symbol lookup error: libtorch_cpu.so: undefined symbol: _ZNK3c1010TensorImpl22is_strides_like_customENS_12MemoryFormatE`

However, I can run the LAMMPS/example/melt successfully. Do you know how to solve it? Thank you very much!

**Comment by phys-chem** [comment]
> When I run pair nequip with compiled LAMMPS, I have this error: `symbol lookup error: libtorch_cpu.so: undefined symbol: _ZNK3c1010TensorImpl22is_strides_like_customENS_12MemoryFormatE`
> 
> However, I can run the LAMMPS/example/melt successfully. Do you know how to solve it? Thank you very much!

It is the problem of compiler. I have solved it. However, when I run LAMMPS, I still get an error:
terminate called after throwing an instance of 'std::out_of_range'
  what():  Argument passed to at() was not in the map.

**Comment by phys-chem** [comment]
> > When I run pair nequip with compiled LAMMPS, I have this error: `symbol lookup error: libtorch_cpu.so: undefined symbol: _ZNK3c1010TensorImpl22is_strides_like_customENS_12MemoryFormatE`
> > However, I can run the LAMMPS/example/melt successfully. Do you know how to solve it? Thank you very much!
> 
> It is the problem of compiler. I have solved it. However, when I run LAMMPS, I still get an error: terminate called after throwing an instance of 'std::out_of_range' what(): Argument passed to at() was not in the map.

It seems that this error is caused by different branches of NequIP and LAMMPS pair. If I want to run NPT, should I used both stress branches for NequIP and pair-NequIP? Could you help me? Thank you very much!

**Comment by Linux-cpp-lisp** [comment]
Should be closed by #52.
