### ISSUE TITLE
 lmp run error:  what():  expected scalar type Float but found Double

### ISSUE THREAD

**Issue by vantasyoscar** [mir-group/pair_nequip#51]
I've compile lammps successfully, but encountered some issues when processing the input files:

`units real
atom_style atomic
newton off
thermo 1
read_data MgS.lmp
pair_style nequip
pair_coeff * * model_e8.pth Mg S
mass 1 24.305    # Mg
mass 2 32.06     # S
neighbor 1.0 bin
neigh_modify delay 5 every 1
velocity all create 300.0 23456789
fix 1 all nvt temp 300.0 300.0 0.5
thermo_style custom step pe ke etotal temp press vol
thermo 100
dump 1 all custom 100 MgS.dump id type x y z
dump 2 all atom 100 MgS.lammpstrj
run 20000
write_data nvt1`

faced with:

`terminate called after throwing an instance of 'c10::Error'
  what():  expected scalar type Float but found Double`

 I’m not sure how to resolve this problem.

**Comment by vantasyoscar** [comment]
I solve this by setting `default_dtype:float32` . Does it mean I must set float32 precision if I want to deploy it on lammps?

**Comment by Linux-cpp-lisp** [comment]
Should be resolved by #52:  you should be able to use the defaults of `nequip` 0.6.0 (`default_dtype: float64`, `model_dtype: float32` with the `main` branch of `pair_nequip`).  We recommend those defaults, and do not recommend setting `default_dtype:float32`.
