### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by deleep225** [mir-group/pair_nequip#7]
Im trying to install in one of our cluster but got the following error.

Make Warning at /home/reddy/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  **static library kineto_LIBRARY-NOTFOUND not found**.
Call Stack (most recent call first):
  /home/reddy/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:922 (find_package)

-- Configuring done
CMake Warning at CMakeLists.txt:142 (add_executable):
  **Cannot generate a safe runtime search path for target lmp because files in
  some directories may conflict with libraries in implicit directories:**

    **runtime library [libgomp.so.1] in /usr/lib64/gcc/x86_64-suse-linux/7 may be hidden by files in:
      /home/reddy/anaconda3/lib
    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /home/reddy/anaconda3/lib**

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/reddy/softwares/lammps-29Sep2021/build

Im able to install the lammps without pair nequip.

**Comment by anjohan** [comment]
Hi deleep,

These look like warnings, not errors? You can try to just run make as usual. The second warning is common when dealing with Anaconda and building stuff.

I haven't seen the first warning before, so I don't know if it is an issue. Google tells me Kineto is some PyTorch profiling library.

Best wishes,
Anders

**Comment by Linux-cpp-lisp** [comment]
The Kineto thing is definitely not a problem, ignore that.
