### ISSUE TITLE
❓ [QUESTION] installation with lammps

### ISSUE THREAD

**Issue by deleep225** [mir-group/pair_nequip#8]
I have done the cmake part successfully in our cluster. 
while doing **make -j 32** i got the following error.

/data/home/reddy/softwares/lammps-29Sep2021/src/pair_nequip.cpp: In member function ‘virtual void LAMMPS_NS::PairNEQUIP::coeff(int, char**)’:
/data/home/reddy/softwares/lammps-29Sep2021/src/pair_nequip.cpp:209:30: error: lvalue required as left operand of assignment
  209 |   torch::jit::getBailoutDepth() = jit_bailout_depth;

I was able to install in my own laptop but got the above error in all of our clusters.

please help me to resolve this issue.
thank you.

**Comment by deleep225** [comment]
@nisargjoshi10 your installation need mkl-libraries or path of them if they are in your system.
please check the below issue

https://github.com/mir-group/nequip/issues/151

**Comment by deleep225** [comment]
@Linux-cpp-lisp I have just installed the nequip with lammps using libtorch1.10.2

Thank you.

However I could not find the **conda** command for installing the pytorch version 1.10.2 (there are only 1.9 and lower versions in conda website), so I have dowloaded the libtorch 1.10.2 version and given that path.

**Comment by Linux-cpp-lisp** [comment]
That works too. For 1.10, you just add something like `conda install pytorch==1.10 ...` with the added `==1.10`.
